version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MINIO_ENDPOINT: minio-server
      MINIO_ACCESS_KEY: 1inch-access-key
      MINIO_SECRET_KEY: 1inch-secret-key
      MINIO_BUCKET_NAME: files
      MONGODB_URI: mongodb://mongodb:27017/1inch
    depends_on:
      - minio-server
      - mongodb
    networks:
      - app-network

  minio-server:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: 1inch-access-key
      MINIO_SECRET_KEY: 1inch-secret-key
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
